console.log('Welcome to JavaScript class')


a = 10;
b = 8;
c = a * b;
console.log(c)
 
var x = 5;
let y = 5;
x =7 
z= x + y;
console.log(z)
k
let lastName = "Jimoh";
let firstName = "Abdulquyum";
let middleName = 'Ishola';
let age = 17
let homeAddress = 'Sabo, Yaba'
console.log(lastName)
console.log(firstName)
console.log(middleName)
console.log(age)
console.log(homeAddress)

let phoneName = 'iPhone X';
let phoneAmount = 376000.201;

console.log(phoneName)
console.log(phoneAmount)

const oddNumber = [1 , 3, 5, 7, 9]
console.log(oddNumber[298])